import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import { afterEach, expect, it } from 'vitest';
import { shellFixture, footer } from './legacy-shared-shell-fixture.mjs';
import { fixture } from './staging-worker-fixture.mjs';
import { createStagingWorker, materializeSelection } from '../server/kernel/staging-worker.js';
import { stagingPacketErrors, continuationErrors } from '../server/kernel/staging-contract.js';
import { Readable } from 'node:stream';
import { createApp } from '../server/kernel/app.js';
import module from '../server/modules/pipeline/index.js';
import { createEvents } from '../server/kernel/events.js';
import { selectedArtifactAuthorization } from '../server/kernel/selected-artifact-authorization.js';
const harness = process.env.NORMAL_SELECTED_RECORDS_HARNESS;
let f;
afterEach(() => { f?.cleanup(); f = null; delete process.env.FAMTASTIC_STUDIO_DISPATCH_SECRET; });
it.skipIf(!harness).each(['intro', 'hero'])('actual callback and request writers derive a %s recipe and authenticated bytes without seeded continuation records', async sectionType => {
  const html = shellFixture().selected.replace('data-section-type="intro"', `data-section-type="${sectionType}"`);
  const raw_callback = JSON.stringify({ event_id: 'normal-event', campaign_id: 'normal-proof', job_id: 'normal-job', variants: ['a', 'b', 'c'].map(direction_id => ({ direction_id, html,
    design_dna: { direction_name: 'Synthetic', spec_snapshot: { extra: {}, list: [], numeric: 1e-7 }, template_path: '/never-follow-callback-path' } })) });
  const request = { project_name: 'Synthetic request', business_name: 'Synthetic', action: 'save', page_count: 2, page_list: 'Home, About', page_content: [{ page_name: 'About', title: 'Our story', description: 'Our authored story', heading: 'Our story', body: 'This is the actual customer supplied page copy.' }] };
  const installation = { artifact_base_url: 'https://agency.example.invalid', authored_shell_policy: { status: 'approved', evidence_ref: 'synthetic-agency-authored-code-policy' },
    targets: { '902': { customer_id: '903', staging_url: 'https://synthetic.famtasticinc.com/', target_path: '/home/nineoo/public_html/synthetic', remote_subdirectory: 'synthetic' } } };
  const call = extra => JSON.parse(execFileSync('php', [harness], { input: JSON.stringify({ raw_callback, request, raw_request: JSON.stringify(extra?.request || request), installation, ...extra }), encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'], maxBuffer: 8 * 1024 * 1024 }));
  const produced = call({});
  const firstSelection = call({ no_project: true });
  expect(firstSelection.projects_created).toBe(1);
  expect(firstSelection.packet).toEqual(produced.packet);
  const p = produced.packet;
  expect(p.schema, JSON.stringify(p.dispatch_issue)).toBe('famtastic.site-studio.build-packet.v1');
  expect(stagingPacketErrors(p)).toEqual([]); expect(continuationErrors(p)).toEqual([]);
  expect(produced.variant_dna).not.toHaveProperty('selected_build_continuation');
  expect(produced.captured_raw_callback).toBe(raw_callback);
  expect(JSON.parse(produced.captured_raw_callback).variants[0].design_dna.spec_snapshot.extra).toEqual({});
  expect(produced.intake.authored_content.raw_input_json).toBe(JSON.stringify(request));
  expect(produced.reader_negatives).toEqual({ bad_signature: true, expired: true, wrong_revision: true });
  const artifact_authorizations = Object.fromEntries(p.artifacts.map(a => [a.sha256, selectedArtifactAuthorization(`${installation.artifact_base_url}/api/site-studio/selected-artifacts/normal-request/1/${a.sha256}`, 'synthetic-reader-secret', 1789600000)]));
  expect(call({ artifact_authorizations }).artifact_bytes).toEqual(produced.artifact_bytes);
  expect(produced.intake.authored_content.pages[0].text.body).toBe(request.page_content[0].body);
  expect(p.continuation.recipe.steps[0].template_provenance).toBe('selected-shell-derivation.v1');
  f = fixture({ producerPacket: p });
  process.env.FAMTASTIC_STUDIO_DISPATCH_SECRET = 'synthetic-normal-secret';
  const app = createApp();
  const worker = createStagingWorker({ ...f.options(), fetchArtifact: async ({ url }) => Buffer.from(produced.artifact_bytes[new URL(url).pathname.split('/').at(-1)], 'base64') });
  let pending;
  module.register({ app, paths: f.paths, journal: f.journal, events: createEvents({ paths: f.paths }), stagingRuntime: { store: f.store, wake: () => pending ||= worker.tick() } });
  const dispatch = () => new Promise(resolve => {
    const req = Readable.from([produced.wire.body]); req.method = 'POST'; req.url = '/api/pipeline/staging/accept'; req.headers = { 'x-famtastic-signature': produced.wire.headers['X-FAMtastic-Signature'] };
    app.handler(req, { writeHead(status) { this.status = status; }, end(body) { resolve({ status: this.status, body: JSON.parse(body) }); } });
  });
  expect((await dispatch()).status).toBe(202); expect((await dispatch()).status).toBe(202);
  await new Promise(resolve => setImmediate(resolve)); await pending;
  const done = f.store.read(f.store.accept(p).id);
  expect(done.failure, JSON.stringify({ build: done.build?.error, failure: done.failure, qa: done.qa?.problems })).toBeUndefined(); expect(done.state).toBe('complete');
  expect(f.remote.get('index.html').toString()).toBe(html);
  expect(f.remote.get('about.html').toString()).toContain(request.page_content[0].body);
  expect(f.remote.get('about.html').toString()).toContain(footer);
  expect(f.counters.generation).toBe(0); expect(f.counters.builds).toBe(1);
  expect((await worker.run(f.store.accept(p).id)).state).toBe('complete'); expect(f.counters.builds).toBe(1);
  expect(call({ receipt: done.callback_body }).receipt_result).toMatchObject({ newly_processed: true, staging_url: p.continuation.hosting_target.staging_url });
  const unchanged = call({ receipt: done.callback_body, accept_review: true, followup_request: request, followup_raw: JSON.stringify(request, null, 2) });
  expect(unchanged.final_packet).toEqual(p);
  expect(unchanged.final_row.staging_review_status).toBe('accepted');
  expect(unchanged.final_state.selected_source_mapping.site_id).toBe(done.source_mapping.site_id);
  const changed = call({ receipt: done.callback_body, accept_review: true, followup_request: { ...request, page_content: [{ ...request.page_content[0], body: 'Changed authored copy.' }] } });
  expect(changed.final_packet.dispatch_issue).toContain('existing_page_copy_requires_edit_recipe');
  expect(changed.final_row.staging_review_status).not.toBe('accepted');
  const homeChange = call({ receipt: done.callback_body, accept_review: true, followup_request: { ...request, page_content: [...request.page_content, { ...request.page_content[0], page_name: 'Home', heading: 'Changed home' }] } });
  expect(homeChange.final_packet.dispatch_issue).toContain('existing_page_copy_requires_edit_recipe:index.html');
  expect(homeChange.final_row.staging_review_status).not.toBe('accepted');
  const removedCopy = call({ receipt: done.callback_body, accept_review: true, followup_request: { ...request, page_content: [] } });
  expect(removedCopy.final_packet.dispatch_issue).toContain('existing_page_copy_removed_requires_review:about.html');
  expect(removedCopy.final_row.staging_review_status).not.toBe('accepted');
  const more = call({ receipt: done.callback_body, accept_review: true, studio_origin: true, followup_request: { ...request, page_count: 3, page_list: 'Home, About, Team', page_content: [...request.page_content, { ...request.page_content[0], page_name: 'Team', title: 'Team', heading: 'Our team' }] } });
  expect(more.final_packet.schema, more.final_packet.dispatch_issue).toBe('famtastic.site-studio.build-packet.v1');
  expect(more.final_packet.continuation.recipe.steps.map(s => s.path)).toEqual(['team.html']);
  expect(more.final_row.staging_review_status).not.toBe('accepted');
  expect(continuationErrors(more.final_packet)).toEqual([]);
  expect(more.final_packet.continuation.initiating_system).toBe('studio');
  expect(more.final_state.selected_source_mapping.originating_system).toBe('designs');
  expect(more.final_state.selected_source_mapping.handoff_initiator).toBe('studio');
  f.restart();
  const worker2 = createStagingWorker({ ...f.options(), fetchArtifact: async ({ url }) => Buffer.from(more.final_artifact_bytes[new URL(url).pathname.split('/').at(-1)], 'base64') });
  const done2 = await worker2.run(f.store.accept(more.final_packet).id);
  expect(done2.state, JSON.stringify({ failure: done2.failure, build: done2.build?.error })).toBe('complete');
  expect(done2.source_mapping.site_id).toBe(done.source_mapping.site_id);
  expect(done2.source_mapping.originating_system).toBe('designs');
  expect(done2.source_mapping.handoff_initiator).toBe('studio');
  expect(f.remote.get('about.html').toString()).toContain(request.page_content[0].body);
  expect(f.remote.get('team.html').toString()).toContain('Our team');
  expect(f.counters.generation).toBe(0);
  expect(() => call({ receipt: { ...done.callback_body, customer_id: 'other' } })).toThrow();
  expect(call({ request: { ...request, page_content: [] } }).packet.dispatch_issue).toContain('authored_copy_missing_about.html');
  expect(call({ request: { ...request, booking_details: 'Accept bookings' } }).packet.dispatch_issue).toContain('unsupported_feature_booking_details');
  expect(call({ installation: { ...installation, authored_shell_policy: {} } }).packet.dispatch_issue).toContain('shell_rights_binding_missing');
}, 20000);

it.skipIf(!harness).each(['callbackFails', 'uploadFails'])('reconciles a verified older agency source through three revisions after %s', async failure => {
  const html = shellFixture().selected;
  const copy = { page_name: 'About', title: 'Our story', description: 'Our story', heading: 'Our story', body: 'Actual authored story.' };
  const request = { project_name: 'Synthetic', business_name: 'Synthetic', action: 'save', page_count: 2, page_list: 'Home, About', page_content: [copy] };
  const team = { ...request, page_count: 3, page_list: 'Home, About, Team', page_content: [copy, { ...copy, page_name: 'Team', title: 'Team', heading: 'Our team' }] };
  const faq = { ...team, page_count: 4, page_list: 'Home, About, Team, FAQ', page_content: [...team.page_content, { ...copy, page_name: 'FAQ', title: 'Questions', heading: 'Your questions' }] };
  const input = { raw_callback: JSON.stringify({ event_id: 'normal-event', campaign_id: 'normal-proof', job_id: 'normal-job', variants: ['a', 'b', 'c'].map(direction_id => ({ direction_id, html, design_dna: {} })) }), request,
    installation: { artifact_base_url: 'https://agency.example.invalid', authored_shell_policy: { status: 'approved', evidence_ref: 'synthetic-owned-code' }, targets: { '902': { customer_id: '903', staging_url: 'https://synthetic.famtasticinc.com/', target_path: '/home/nineoo/public_html/synthetic', remote_subdirectory: 'synthetic' } } } };
  const call = extra => JSON.parse(execFileSync('php', [harness], { input: JSON.stringify({ ...input, ...extra }), encoding: 'utf8', maxBuffer: 12 * 1024 * 1024 }));
  const initial = call({}); f = fixture({ producerPacket: initial.packet });
  const workerFor = bytes => createStagingWorker({ ...f.options(), fetchArtifact: async ({ url }) => Buffer.from(bytes[new URL(url).pathname.split('/').at(-1)], 'base64') });
  const first = await workerFor(initial.artifact_bytes).run(f.store.accept(initial.packet).id);
  expect(first.state).toBe('complete');
  const aboutBytes = Buffer.from(f.remote.get('about.html'));
  const secondInput = call({ receipt: first.callback_body, followup_request: team });
  f.controls[failure] = true;
  const secondId = f.store.accept(secondInput.final_packet).id;
  const second = await workerFor(secondInput.final_artifact_bytes).run(secondId);
  expect(second.state).toBe('retry'); expect(second.source_mapping.source_export_sha256).not.toBe(first.source_mapping.source_export_sha256);
  const teamBytes = fs.readFileSync(f.paths.within('sites', second.build.site_id, 'team.html'));
  const thirdInput = call({ receipt: first.callback_body, followup_requests: [team, faq] });
  const packet = thirdInput.final_packet;
  expect(packet.continuation.selection_revision).toBe(3);
  expect(packet.continuation.source_export_sha256).toBe(first.source_mapping.source_export_sha256);
  expect(packet.continuation.recipe.steps.map(s => s.path)).toEqual(['team.html', 'faq.html']);
  f.restart(); f.controls[failure] = false;
  const unknown = structuredClone(packet); unknown.continuation.source_export_sha256 = 'f'.repeat(64);
  await expect(f.store.resolveCompleted(unknown)).rejects.toThrow('source_repository_mapping_stale');
  const tampered = structuredClone(packet); tampered.artifacts.find(a => a.path.endsWith('/about.html')).sha256 = 'e'.repeat(64);
  await expect(f.store.resolveCompleted(tampered)).rejects.toThrow('source_repository_ancestor_bytes_changed');
  const unrelated = structuredClone(packet); unrelated.continuation.customer.id = 'other';
  await expect(f.store.resolveCompleted(unrelated)).rejects.toThrow('source_repository_mapping_required');
  const changed = call({ receipt: first.callback_body, followup_requests: [team, { ...faq, page_content: faq.page_content.map(p => p.page_name === 'Team' ? { ...p, body: 'Changed team copy.' } : p) }] });
  await expect(materializeSelection(changed.final_packet, { ...f.options(), resolveCompleted: f.store.resolveCompleted, readMappedArtifact: f.store.readMappedArtifact,
    fetchArtifact: async ({ url }) => Buffer.from(changed.final_artifact_bytes[new URL(url).pathname.split('/').at(-1)], 'base64') })).rejects.toThrow('completed_page_copy_requires_edit_recipe');
  const thirdWorker = workerFor(thirdInput.final_artifact_bytes), thirdId = f.store.accept(packet).id;
  const done = await thirdWorker.run(thirdId);
  expect(done.state, JSON.stringify({ failure: done.failure, error: done.build?.error })).toBe('complete');
  expect(done.selected.transformations.map(t => t.path)).toEqual(['faq.html']);
  expect(done.selected.execution_packet.local_source_reconciliation.reused_pages).toEqual(['team.html']);
  expect(done.build.repository.repository_path).toBe(first.build.repository.repository_path);
  expect(f.remote.get('about.html')).toEqual(aboutBytes);
  expect(f.remote.get('team.html')).toEqual(teamBytes);
  expect(f.remote.get('faq.html').toString()).toContain('Your questions');
  expect(done.packet).toEqual(packet);
  expect((await thirdWorker.run(secondId)).state).toBe('superseded');
  expect((await thirdWorker.run(thirdId)).state).toBe('complete');
  expect(f.counters.builds).toBe(3); expect(f.counters.generation).toBe(0);
}, 20000);

it.skipIf(!harness)('packages a non-intro Home source without assembling or generating pages', async () => {
  const html = shellFixture().selected.replace('data-section-type="intro"', 'data-section-type="hero"').replace('href="about.html"', 'href="#main"');
  const input = { no_project: true,
    raw_callback: JSON.stringify({ event_id: 'normal-event', campaign_id: 'normal-proof', job_id: 'normal-job', variants: ['a', 'b', 'c'].map(direction_id => ({ direction_id, html, design_dna: {} })) }),
    request: { project_name: 'Synthetic', business_name: 'Synthetic', action: 'save', page_count: 1, page_list: 'Home' },
    installation: { artifact_base_url: 'https://agency.example.invalid', authored_shell_policy: { status: 'approved', evidence_ref: 'synthetic-owned-code' }, targets: { '902': { customer_id: '903', staging_url: 'https://synthetic.famtasticinc.com/', target_path: '/home/nineoo/public_html/synthetic', remote_subdirectory: 'synthetic' } } } };
  const produced = JSON.parse(execFileSync('php', [harness], { input: JSON.stringify(input), encoding: 'utf8' }));
  expect(produced.packet.continuation.operation).toBe('package_existing');
  expect(produced.packet.continuation.recipe).toBeUndefined();
  f = fixture({ producerPacket: produced.packet });
  const worker = createStagingWorker({ ...f.options(), fetchArtifact: async ({ url }) => Buffer.from(produced.artifact_bytes[new URL(url).pathname.split('/').at(-1)], 'base64') });
  const done = await worker.run(f.store.accept(produced.packet).id);
  expect(done.state, JSON.stringify(done.failure)).toBe('complete');
  expect(f.remote.get('index.html').toString()).toBe(html);
  expect(f.counters.generation).toBe(0);
  expect(done.build.transformations || []).toEqual([]);
});

it.skipIf(!harness).each(['callbackFails', 'uploadFails'])('reconciles completed pages after %s without waiting for the agency receipt', async failure => {
  const html = shellFixture().selected;
  const copy = { page_name: 'About', title: 'Our story', description: 'Our story', heading: 'Our story', body: 'Actual authored story.' };
  const request = { project_name: 'Synthetic', business_name: 'Synthetic', action: 'save', page_count: 2, page_list: 'Home, About', page_content: [copy] };
  const input = { raw_callback: JSON.stringify({ event_id: 'normal-event', campaign_id: 'normal-proof', job_id: 'normal-job', variants: ['a', 'b', 'c'].map(direction_id => ({ direction_id, html, design_dna: {} })) }), request,
    installation: { artifact_base_url: 'https://agency.example.invalid', authored_shell_policy: { status: 'approved', evidence_ref: 'synthetic-owned-code' }, targets: { '902': { customer_id: '903', staging_url: 'https://synthetic.famtasticinc.com/', target_path: '/home/nineoo/public_html/synthetic', remote_subdirectory: 'synthetic' } } } };
  const call = extra => JSON.parse(execFileSync('php', [harness], { input: JSON.stringify({ ...input, ...extra }), encoding: 'utf8', maxBuffer: 8 * 1024 * 1024 }));
  const first = call({}); f = fixture({ producerPacket: first.packet });
  f.controls[failure] = true;
  const worker = createStagingWorker({ ...f.options(), fetchArtifact: async ({ url }) => Buffer.from(first.artifact_bytes[new URL(url).pathname.split('/').at(-1)], 'base64') });
  const oldId = f.store.accept(first.packet).id, interrupted = await worker.run(oldId);
  expect(interrupted.state).toBe('retry'); expect(interrupted.source_mapping).toBeTruthy();
  const before = await import('node:fs').then(fs => fs.readFileSync(f.paths.within('sites', interrupted.build.site_id, 'about.html')));
  const next = call({ followup_request: { ...request, page_count: 3, page_list: 'Home, About, Team', page_content: [copy, { ...copy, page_name: 'Team', title: 'Team', heading: 'Our team' }] } });
  expect(next.final_packet.continuation.source_export_sha256).toBeUndefined();
  expect(next.final_packet.continuation.recipe.steps.map(s => s.path)).toEqual(['about.html', 'team.html']);
  const changed = call({ followup_request: { ...request, page_content: [{ ...copy, body: 'Changed while callback was delayed.' }] } });
  await expect(materializeSelection(changed.final_packet, { ...f.options(), resolveCompleted: f.store.resolveCompleted, readMappedArtifact: f.store.readMappedArtifact,
    fetchArtifact: async ({ url }) => Buffer.from(changed.final_artifact_bytes[new URL(url).pathname.split('/').at(-1)], 'base64') })).rejects.toThrow('completed_page_copy_requires_edit_recipe');
  expect(f.counters.builds).toBe(1);
  f.controls[failure] = false; f.restart();
  const nextWorker = createStagingWorker({ ...f.options(), fetchArtifact: async ({ url }) => Buffer.from(next.final_artifact_bytes[new URL(url).pathname.split('/').at(-1)], 'base64') });
  const id = f.store.accept(next.final_packet).id, done = await nextWorker.run(id);
  expect(done.state, JSON.stringify({ failure: done.failure, error: done.build?.error })).toBe('complete');
  expect(done.selected.transformations.map(t => t.path)).toEqual(['team.html']);
  expect(done.selected.execution_packet.local_source_reconciliation.reused_pages).toEqual(['about.html']);
  expect(done.packet).toEqual(next.final_packet);
  expect(f.remote.get('about.html')).toEqual(before);
  expect(done.build.repository.repository_path).toBe(interrupted.build.repository.repository_path);
  expect(f.counters.builds).toBe(2); expect(f.counters.generation).toBe(0);
  expect((await nextWorker.run(id)).state).toBe('complete');
  expect((await nextWorker.run(oldId)).state).toBe('superseded');
  expect(f.counters.builds).toBe(2);
}, 20000);
