import { execFileSync } from 'node:child_process';
import { afterEach, expect, it } from 'vitest';
import { shellFixture, footer } from './legacy-shared-shell-fixture.mjs';
import { fixture } from './staging-worker-fixture.mjs';
import { createStagingWorker } from '../server/kernel/staging-worker.js';
import { stagingPacketErrors, continuationErrors } from '../server/kernel/staging-contract.js';
import { Readable } from 'node:stream';
import { createApp } from '../server/kernel/app.js';
import module from '../server/modules/pipeline/index.js';
import { createEvents } from '../server/kernel/events.js';
import { selectedArtifactAuthorization } from '../server/kernel/selected-artifact-authorization.js';
const harness = process.env.NORMAL_SELECTED_RECORDS_HARNESS;
let f;
afterEach(() => { f?.cleanup(); f = null; delete process.env.FAMTASTIC_STUDIO_DISPATCH_SECRET; });
it.skipIf(!harness)('actual callback and request writers derive a recipe and authenticated bytes without seeded continuation records', async () => {
  const html = shellFixture().selected;
  const raw_callback = JSON.stringify({ event_id: 'normal-event', campaign_id: 'normal-proof', job_id: 'normal-job', variants: ['a', 'b', 'c'].map(direction_id => ({ direction_id, html,
    design_dna: { direction_name: 'Synthetic', spec_snapshot: { extra: {}, list: [], numeric: 1e-7 }, template_path: '/never-follow-callback-path' } })) });
  const request = { project_name: 'Synthetic request', business_name: 'Synthetic', action: 'save', page_count: 2, page_list: 'Home, About', page_content: [{ page_name: 'About', title: 'Our story', description: 'Our authored story', heading: 'Our story', body: 'This is the actual customer supplied page copy.' }] };
  const installation = { artifact_base_url: 'https://agency.example.invalid', authored_shell_policy: { status: 'approved', evidence_ref: 'synthetic-agency-authored-code-policy' },
    targets: { '902': { customer_id: '903', staging_url: 'https://synthetic.famtasticinc.com/', target_path: '/home/nineoo/public_html/synthetic', remote_subdirectory: 'synthetic' } } };
  const call = extra => JSON.parse(execFileSync('php', [harness], { input: JSON.stringify({ raw_callback, request, raw_request: JSON.stringify(extra?.request || request), installation, ...extra }), encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'], maxBuffer: 8 * 1024 * 1024 }));
  const produced = call({});
  const p = produced.packet;
  expect(p.schema, JSON.stringify(p.dispatch_issue)).toBe('famtastic.site-studio.build-packet.v1');
  expect(stagingPacketErrors(p)).toEqual([]); expect(continuationErrors(p)).toEqual([]);
  expect(produced.variant_dna).not.toHaveProperty('selected_build_continuation');
  expect(produced.captured_raw_callback).toBe(raw_callback);
  expect(JSON.parse(produced.captured_raw_callback).variants[0].design_dna.spec_snapshot.extra).toEqual({});
  expect(produced.intake.authored_content.raw_input_json).toBe(JSON.stringify(request));
  expect(produced.reader_negatives).toEqual({ bad_signature: true, expired: true, wrong_revision: true });
  const artifact_authorizations = Object.fromEntries(p.artifacts.map(a => [a.sha256, selectedArtifactAuthorization(`${installation.artifact_base_url}/api/site-studio/selected-artifacts/normal-request/1/${a.sha256}`, 'synthetic-reader-secret', 1789600000)]));
  expect(call({ artifact_authorizations }).artifact_bytes).toEqual(produced.artifact_bytes);
  expect(produced.intake.authored_content.pages[0].text.body).toBe(request.page_content[0].body);
  expect(p.continuation.recipe.steps[0].template_provenance).toBe('selected-shell-derivation.v1');
  f = fixture({ producerPacket: p });
  process.env.FAMTASTIC_STUDIO_DISPATCH_SECRET = 'synthetic-normal-secret';
  const app = createApp();
  const worker = createStagingWorker({ ...f.options(), fetchArtifact: async ({ url }) => Buffer.from(produced.artifact_bytes[new URL(url).pathname.split('/').at(-1)], 'base64') });
  let pending;
  module.register({ app, paths: f.paths, journal: f.journal, events: createEvents({ paths: f.paths }), stagingRuntime: { store: f.store, wake: () => pending ||= worker.tick() } });
  const dispatch = () => new Promise(resolve => {
    const req = Readable.from([produced.wire.body]); req.method = 'POST'; req.url = '/api/pipeline/staging/accept'; req.headers = { 'x-famtastic-signature': produced.wire.headers['X-FAMtastic-Signature'] };
    app.handler(req, { writeHead(status) { this.status = status; }, end(body) { resolve({ status: this.status, body: JSON.parse(body) }); } });
  });
  expect((await dispatch()).status).toBe(202); expect((await dispatch()).status).toBe(202);
  await new Promise(resolve => setImmediate(resolve)); await pending;
  const done = f.store.read(f.store.accept(p).id);
  expect(done.failure, JSON.stringify({ build: done.build?.error, failure: done.failure, qa: done.qa?.problems })).toBeUndefined(); expect(done.state).toBe('complete');
  expect(f.remote.get('index.html').toString()).toBe(html);
  expect(f.remote.get('about.html').toString()).toContain(request.page_content[0].body);
  expect(f.remote.get('about.html').toString()).toContain(footer);
  expect(f.counters.generation).toBe(0); expect(f.counters.builds).toBe(1);
  expect((await worker.run(f.store.accept(p).id)).state).toBe('complete'); expect(f.counters.builds).toBe(1);
  expect(call({ receipt: done.callback_body }).receipt_result).toMatchObject({ newly_processed: true, staging_url: p.continuation.hosting_target.staging_url });
  expect(() => call({ receipt: { ...done.callback_body, customer_id: 'other' } })).toThrow();
  expect(call({ request: { ...request, page_content: [] } }).packet.dispatch_issue).toContain('authored_copy_missing_about.html');
  expect(call({ request: { ...request, booking_details: 'Accept bookings' } }).packet.dispatch_issue).toContain('unsupported_feature_booking_details');
  expect(call({ installation: { ...installation, authored_shell_policy: {} } }).packet.dispatch_issue).toContain('shell_rights_binding_missing');
});
